import { getOracleConnection } from './oracleClient.js'
export async function createPostTable() {
	const connection = await getOracleConnection()

	try {
		// Check if the posts table exists
		const result = await connection.execute(`
      SELECT table_name FROM user_tables WHERE table_name = 'POSTS'
    `)

		if (result.rows.length === 0) {
			// Create the posts table if it does not exist
			await connection.execute(`
        CREATE TABLE posts (
          id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          username VARCHAR2(50) NOT NULL,
          postImage VARCHAR2(255) NOT NULL,
          postText VARCHAR2(255) NOT NULL,
		  
          created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
      `)
			console.log('Posts table created successfully')
		} else {
			console.log('Posts table already exists')
		}

		// Add more table creation logic here if needed
	} catch (error) {
		console.error('Error creating tables:', error)
	} finally {
		await connection.close()
	}
}
