import { getOracleConnection } from './oracleClient.js'
export async function createLikesTable() {
	const connection = await getOracleConnection()

	try {
		// Check if the likes table exists
		const result = await connection.execute(`
      SELECT table_name FROM user_tables WHERE table_name = 'LIKES'
    `)

		if (result.rows.length === 0) {
			// Create the likes table if it does not exist
			await connection.execute(`
        CREATE TABLE likes (
          id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          postid NUMBER NOT NULL,
          userid NUMBER NOT NULL,
          created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
          FOREIGN KEY (postid) REFERENCES posts(id),
          FOREIGN KEY (userid) REFERENCES users(id)
        )
      `)
			console.log('Likes table created successfully')
		} else {
			console.log('Likes table already exists')
		}
	} catch (error) {
		console.error('Error creating likes table:', error)
	} finally {
		await connection.close()
	}
}
